SELECT TOP (1000) [anio]
      ,[mes]
      ,[documento]
      ,[carrera_id]
      ,[titulo_id]
      ,[numero_resolucion]
      ,[fecha_resolucion]
      ,[tipo_institucion_id]
      ,[institucion_id]
      ,[sexo]
  FROM [titulos].[dbo].[registros_titulos]
